name: Haskell CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        allow-fail: [false]
        plan:
          - build: cabal
            ghc: latest
          - build: cabal
            ghc: '9.0.1'
          - build: stack
            ghc: '8.10.3'
            resolver: 'lts-17.2'
          - build: stack
            ghc: '8.8.3'
            resolver: 'lts-16.11'
          - build: stack
            ghc: '8.6.5'
            resolver: 'lts-14.27'
        include:
          - plan: { build: cabal, ghc: latest }
            allow-fail: true
           
    continue-on-error: ${{ matrix.plan.allow-fail }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.plan.ghc }}
        enable-stack: true

    #### Disable caching for now.
    
    ## - name: Cache
    ##   uses: actions/cache@v1
    ##   env:
    ##     cache-name: cache-cabal
    ##   with:
    ##     path: ~/.cabal
    ##     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
    ##     restore-keys: |
    ##       ${{ runner.os }}-build-${{ env.cache-name }}-
    ##       ${{ runner.os }}-build-
    ##       ${{ runner.os }}-

    - name: Install dependencies
      env:
        BUILD: ${{ matrix.plan.build }}
        RESOLVER: ${{ matrix.plan.resolver }}
      run: |
        set -ex
        case "$BUILD" in
          stack)
            stack --no-terminal --system-ghc --resolver $RESOLVER test --bench --only-dependencies
            ;;
          cabal)
            rm -f cabal.project.freeze
            cabal v2-update
            cabal v2-configure --enable-tests --enable-benchmarks --test-show-details streaming
            cabal v2-build --only-dependencies all
            ;;
        esac
        set +ex
    - name: Build
      env:
        BUILD: ${{ matrix.plan.build }}
        RESOLVER: ${{ matrix.plan.resolver }}
      run: |
        set -ex
        case "$BUILD" in
          stack)
            stack --no-terminal --system-ghc --resolver $RESOLVER build --bench --haddock --no-haddock-deps
            ;;
          cabal)
            cabal v2-build all
            cabal v2-haddock all
            ;;
        esac
        set +ex
    - name: Test
      env:
        BUILD: ${{ matrix.plan.build }}
        RESOLVER: ${{ matrix.plan.resolver }}
      run: |
        set -ex
        case "$BUILD" in
          stack)
            stack --no-terminal --system-ghc -j 1 --resolver $RESOLVER test --bench --no-run-benchmarks --haddock --no-haddock-deps
            ;;
          cabal)
            cabal v2-test --jobs=1 all
            ;;
        esac
        set +ex

